#
#      Analyse
# Version - ${pluginVersion}
#
# Use https://docs.analyse.net for plugin documentation.

server:
  id: ''
  token: ''

hooks:
  papi: true

excluded:
  # Exclude players by their UUID.
  players: []
  # Example:
  # players:
  #   - 'ed6daf33-575b-460b-a2f3-e208a1004c10'

# The minimum duration (seconds) that a player must play for
# in order to be counted. This is useful to prevent players logging
# in and out (e.g. a hub) being treated as a player.
minimum-session-duration: 30

# Event configuration
# These settings control how events are sent to Analyse.
events:
  # The following events are sent to Analyse for tracking.
  # Analyse does not track events, you must implement them yourself.
  # Any event that is not listed here will not be sent to Analyse, and sent as a warning to the console.
  list:
    - 'kills'
    - 'deaths'
    - 'blocks_broken'
    - 'blocks_placed'
    - 'commands'



# *** DEBUGGING PURPOSES ONLY ***
# You should not change these values unless you know what you are doing.
#
# ALL - Logs extra insights and event information to the console.
# EVENTS - Logs event information to the console.
# NONE - Disables all debugging.
#
debug-mode: "NONE"

#
# *** DO NOT MODIFY OR SHARE THIS KEY ***
#
# The below key is automatically generated for your server.
# It is used to encrypt sensitive information, such as player IP addresses
# which can then ONLY be decrypted by this server.
#
# *** DO NOT MODIFY OR SHARE THIS KEY ***
#
encryption-key: ''