name: Analyse
main: net.analyse.base.platform.bukkit.BukkitAnalysePlatform
version: ${pluginVersion}
author: "Analyse"
website: "https://analyse.net"
description: "Understand your Minecraft audience and monetise your server better."
api-version: "1.13"
softdepend:
  - "PlaceholderAPI"
commands:
  analyse:
    description: Main command of the plugin